### ISSUE TITLE
Security guidelines

### ISSUE THREAD

**Issue by lostrogit** [Bildungsportal/moodle-local_table_sql#7]
I would suggest avoid directly accessing to $_POST in [this](https://github.com/Bildungsportal/moodle-local_table_sql/blob/main/classes/table_sql_subform.php#L74) method, in order to comply with the security policy https://moodledev.io/general/development/policies/security#dont-trust-any-input-from-users

**Comment by rschrenk** [comment]
I have found no other solution, but the Post-Vars are validated later using the Moodle mechanics. They are only put into another structure to comply with the Moodle standards, after they have been packed by a Javascript in
- https://github.com/Bildungsportal/moodle-local_table_sql/blob/f961ceb1148370177deb11cc92877ae339ace77c/amd/src/form.js#L120
