### ISSUE TITLE
code seems to include MIT licensed react code?

### ISSUE THREAD

**Issue by danmarsden** [Bildungsportal/moodle-local_table_sql#8]
including other libraries copied from other locations is ok if the license associated complies with GPL, but you also need to include a thirdpartylibs.xml file that details this and what licence it uses.

More information on this is here:
https://moodledev.io/docs/apis/commonfiles#thirdpartylibsxml
And here:
https://moodledev.io/general/community/plugincontribution/thirdpartylibraries

One of the other advantages of using this is that Moodle's codechecker automatically ignores any files included in the location specificed in the thirdpartylibs.xml file.

Please note - this is typically a blocker for approval in the plugins db.

**Comment by danmarsden** [comment]
ah - looks like you've partially covered this in: https://github.com/Bildungsportal/moodle-local_table_sql/blob/main/LICENSE.js.txt

but just missing the thirdpartylibs.xml file.

**Comment by rschrenk** [comment]
We added the [thirdpartylibs.xml](https://github.com/Bildungsportal/moodle-local_table_sql/blob/main/thirdpartylibs.xml) to the current release. It will move to the Moodle plugins database once we publish an incremented version.
